apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: "hamarawill"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "Welcome@2025"
            - name: PGDATA  # ✅ Fix for lost+found issue
              value: "/var/lib/postgresql/data"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql  # ✅ Mount at a higher level
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pvc
